### ISSUE TITLE
Input标签clearInput属性bug

### ISSUE THREAD

**Issue by xumingxin7398** [vm-component/vimo#22]
clearInput属性点击右侧清除无效，且当type=password时进行输入框的删除和输入操作出现异常。

**Comment by xiangsongtao** [comment]
这个问题在最新的vimo版本中已修复，这部分改动很大，包括替换SCSS，使用babel-plugin-import支持懒加载等，如果你这边升级估计改动会比较大。

**Comment by xiangsongtao** [comment]
建议你使用的版本下载后在项目中手动更新

**Comment by xumingxin7398** [comment]
如果改动已经提交，希望可以更新一下文档

**Comment by xumingxin7398** [comment]
我看了一下演示demo，用法还是旧的有问题的
